apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-k3s
spec:
  provider:
    vault:
      server: "http://10.0.20.110:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: vault-auth
            namespace: external-secrets
            audiences:
              - "https://kubernetes.default.svc.cluster.local"