apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-secret
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-k3s
    kind: ClusterSecretStore
  target:
    name: demo-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: apps/demo
        property: username
    - secretKey: password
      remoteRef:
        key: apps/demo
        property: password