preUpgradeChecker:
  jobEnabled: false

defaultSettings:
  defaultReplicaCount: 1
  backupTarget: ""
  backupTargetCredentialSecret: ""

persistence:
  defaultClass: false
  defaultClassReplicaCount: 1

longhornUI:
  replicas: 1