apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgadmin-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  source:
    repoURL: https://github.com/MosheAzraf/proxmox-iac-k3s-lab
    targetRevision: main
    path: _kubernetes/platform/pgadmin/configs

  destination:
    server: https://kubernetes.default.svc
    namespace: pgadmin

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true