---
# Runs locally and requires Helm + kubeconfig configured on the development machine
- name: add metallb helm repo
  kubernetes.core.helm_repository:
    name: "{{ metallb_repo_name }}"
    repo_url: "{{ metallb_repo_url }}"

- name: install metallb
  kubernetes.core.helm:
    name: "{{ metallb_release_name }}"
    chart_ref: "{{ metallb_chart }}"
    release_namespace: "{{ metallb_namespace }}"
    create_namespace: true
    chart_version: "{{ metallb_chart_version }}"
    state: present

- name: configure metallb ip pool
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'ip-address-pool.yaml.j2') | from_yaml }}"

- name: configure metallb l2 advertisement
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'l2-advertisement.yaml.j2') | from_yaml }}"

