---
- name: add traefik helm repo
  kubernetes.core.helm_repository:
    name: "{{ traefik_repo_name }}"
    repo_url: "{{ traefik_repo_url }}"

- name: install traefik
  kubernetes.core.helm:
    name: "{{ traefik_release_name }}"
    chart_ref: "{{ traefik_chart }}"
    release_namespace: "{{ traefik_namespace }}"
    create_namespace: true
    chart_version: "{{ traefik_chart_version }}"
    state: present