---
# k3s vars
k3s_version: "v1.35.4+k3s1"

# metallb
metallb_namespace: "metallb-system"
metallb_release_name: "metallb"
metallb_chart: "metallb/metallb"
metallb_repo_name: "metallb"
metallb_repo_url: "https://metallb.github.io/metallb"
metallb_chart_version: "0.15.3"

#metallb ip pool
metallb_ip_range: "10.0.20.200-10.0.20.230"
metallb_address_pool_name: "default-pool"
metallb_l2_advertisement_name: "default-l2"

# traefik
traefik_namespace: "traefik"
traefik_release_name: "traefik"
traefik_chart: "traefik/traefik"
traefik_repo_name: "traefik"
traefik_repo_url: "https://traefik.github.io/charts"
traefik_chart_version: "40.2.0"

#argocd
argocd_repo_name: argo
argocd_namespace: argocd
argocd_release_name: argocd
argocd_chart: argo/argo-cd
argocd_repo_url: https://argoproj.github.io/argo-helm
argocd_chart_version: 9.5.14

#cert-manager
cert_manager_repo_name: jetstack
cert_manager_namespace: cert-manager
cert_manager_release_name: cert-manager
cert_manager_chart: jetstack/cert-manager
cert_manager_repo_url: https://charts.jetstack.io
cert_manager_chart_version: 1.20.2
cert_manager_crds_enabled: true