apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-secret
  namespace: pgadmin
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-k3s
    kind: ClusterSecretStore
  target:
    name: pgadmin-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: password
      remoteRef:
        key: apps/pgadmin
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore