apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homarr-db-encryption
  namespace: homarr
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-k3s
    kind: ClusterSecretStore
  target:
    name: db-encryption
    creationPolicy: Owner
  data:
    - secretKey: db-encryption-key
      remoteRef:
        key: apps/homarr
        property: db-encryption-key